title: pableins.com
remote_theme: jekyll/minima
google_analytics: G-NZY6KN9459

show_excerpts: true

header_pages:
  - blog.md
  - series/index.md
  - about.md

minima:
  skin: dark

plugins:
 - jekyll-feed
 - jekyll-seo-tag 
