title: pableins.com
remote_theme: jekyll/minima
google_analytics: G-NZY6KN9459

description: >
  Welcome, here you can find information about
  projects that I am working on at the moment
  and past projects as well.

show_excerpts: true

header_pages:
  - about.md

minima:
  skin: dark
  
  social_links:
    github: pablinme
    twitter: pablinme
    telegram: pablinme

plugins:
 - jekyll-feed
 - jekyll-seo-tag 
