title: pableins.com
remote_theme: jekyll/minima
google_analytics: G-NZY6KN9459

header_pages:
  - about.md

show_excerpts: false

minima:
  skin: dark
  
  social_links:
    github: pablinme
    twitter: pablinme
    telegram: pablinme

plugins:
 - jekyll-feed
 - jekyll-seo-tag 
